spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/sdp_fsad_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Remyy}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server config
server.port=${PORT:8080}
server.error.include-message=always

# Multipart Configuration (allow large images up to 10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT secret (should be externalized in real prod)
jwt.secret=${JWT_SECRET:4f71a067a99b422a84a6558e6f1a8c3e1e9766bb4f145adcb9e2a39f60af0256}
jwt.expiration=86400000

# Mail Configuration (Example for Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=2400031394cse@gmail.com
spring.mail.password=xbuz npua cvjk ehvh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Twilio SMS Configuration
twilio.account-sid=ACd74efbcbe3791bd75ca7907c43a01140
twilio.auth-token=60a48590cc4e2b387b69bf191eba4fa6
twilio.phone-number=+19785413474

# Admin Seeder Configuration
admin1.email=admin1@gmail.com
admin1.password=admin123
admin2.email=admin2@gmail.com
admin2.password=admin123